name: birthdayboy
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  page_view_dot_indicator: ^2.0.0
  flutter_image_slideshow: any
  flutter_svg: ^0.22.0
  syncfusion_flutter_datepicker: ^20.3.52
  convex_bottom_bar: ^3.0.0
  persistent_bottom_nav_bar: any
  flutter_dialogs: ^3.0.0
  flutter_smart_dialog: ^4.6.2+1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Rubik
      fonts: 
        - asset: assets/fonts/RubikMedium.ttf
          weight: 500
        - asset: assets/fonts/RubikBold.ttf
          weight: 700
        - asset: assets/fonts/RubikRegular.ttf
          weight: 400
        - asset: assets/fonts/RubikBlack.ttf
          weight: 900
        - asset: assets/fonts/RubikSemiBold.ttf
          weight: 600
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
